package br.com.quintoandar.javajwt

import org.jose4j.jwt.consumer.InvalidJwtException
import spock.lang.Shared
import spock.lang.Specification

class QuintoAndarKeycloakJwtSpec extends Specification {

  @Shared
  def keycloakPublicKeyServiceMock = Mock(QuintoAndarKeycloakPublicKeyService)

  @Shared
  def keycloakSubject = GroovySpy(QuintoAndarKeycloakJwtBean)

  @Shared
  def fakePublicKey2048bit = "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AM\n" +
      "IIBCgKCAQEAnzyis1ZjfNB0bBgKFMSvvkTtwlvBsaJq7S5wA+kzeVOVpVWwkWdVh\n" +
      "a4s38XM/pa/yr47av7+z3VTmvDRyAHcaT92whREFpLv9cj5lTeJSibyr/Mrm/Ytj\n" +
      "CZVWgaOYIhwrXwKLqPr/11inWsAkfIytvHWTxZYEcXLgAXFuUuaS3uF9gEiNQwzG\n" +
      "TU1v0FqkqTBr4B8nW3HCN47XUu0t8Y0e+lf4s4OxQawWD79J9/5d3Ry0vbV3Am1F\n" +
      "tGJiJvOwRsIfVChDpYStTcHTCMqtvWbV6L11BWkpzGXSW4Hv43qa+GSYOD2QU68M\n" +
      "b59oSk2OB+BtOLpJofmbGEGgvmwyCI9MwIDAQAB"

  @Shared
  def fakePrivateKey2048bit = "-----BEGIN PRIVATE KEY-----\n" +
      "MIIEogIBAAKCAQEAnzyis1ZjfNB0bBgKFMSvvkTtwlvBsaJq7S5wA+kzeVOVpVWw\n" +
      "kWdVha4s38XM/pa/yr47av7+z3VTmvDRyAHcaT92whREFpLv9cj5lTeJSibyr/Mr\n" +
      "m/YtjCZVWgaOYIhwrXwKLqPr/11inWsAkfIytvHWTxZYEcXLgAXFuUuaS3uF9gEi\n" +
      "NQwzGTU1v0FqkqTBr4B8nW3HCN47XUu0t8Y0e+lf4s4OxQawWD79J9/5d3Ry0vbV\n" +
      "3Am1FtGJiJvOwRsIfVChDpYStTcHTCMqtvWbV6L11BWkpzGXSW4Hv43qa+GSYOD2\n" +
      "QU68Mb59oSk2OB+BtOLpJofmbGEGgvmwyCI9MwIDAQABAoIBACiARq2wkltjtcjs\n" +
      "kFvZ7w1JAORHbEufEO1Eu27zOIlqbgyAcAl7q+/1bip4Z/x1IVES84/yTaM8p0go\n" +
      "amMhvgry/mS8vNi1BN2SAZEnb/7xSxbflb70bX9RHLJqKnp5GZe2jexw+wyXlwaM\n" +
      "+bclUCrh9e1ltH7IvUrRrQnFJfh+is1fRon9Co9Li0GwoN0x0byrrngU8Ak3Y6D9\n" +
      "D8GjQA4Elm94ST3izJv8iCOLSDBmzsPsXfcCUZfmTfZ5DbUDMbMxRnSo3nQeoKGC\n" +
      "0Lj9FkWcfmLcpGlSXTO+Ww1L7EGq+PT3NtRae1FZPwjddQ1/4V905kyQFLamAA5Y\n" +
      "lSpE2wkCgYEAy1OPLQcZt4NQnQzPz2SBJqQN2P5u3vXl+zNVKP8w4eBv0vWuJJF+\n" +
      "hkGNnSxXQrTkvDOIUddSKOzHHgSg4nY6K02ecyT0PPm/UZvtRpWrnBjcEVtHEJNp\n" +
      "bU9pLD5iZ0J9sbzPU/LxPmuAP2Bs8JmTn6aFRspFrP7W0s1Nmk2jsm0CgYEAyH0X\n" +
      "+jpoqxj4efZfkUrg5GbSEhf+dZglf0tTOA5bVg8IYwtmNk/pniLG/zI7c+GlTc9B\n" +
      "BwfMr59EzBq/eFMI7+LgXaVUsM/sS4Ry+yeK6SJx/otIMWtDfqxsLD8CPMCRvecC\n" +
      "2Pip4uSgrl0MOebl9XKp57GoaUWRWRHqwV4Y6h8CgYAZhI4mh4qZtnhKjY4TKDjx\n" +
      "QYufXSdLAi9v3FxmvchDwOgn4L+PRVdMwDNms2bsL0m5uPn104EzM6w1vzz1zwKz\n" +
      "5pTpPI0OjgWN13Tq8+PKvm/4Ga2MjgOgPWQkslulO/oMcXbPwWC3hcRdr9tcQtn9\n" +
      "Imf9n2spL/6EDFId+Hp/7QKBgAqlWdiXsWckdE1Fn91/NGHsc8syKvjjk1onDcw0\n" +
      "NvVi5vcba9oGdElJX3e9mxqUKMrw7msJJv1MX8LWyMQC5L6YNYHDfbPF1q5L4i8j\n" +
      "8mRex97UVokJQRRA452V2vCO6S5ETgpnad36de3MUxHgCOX3qL382Qx9/THVmbma\n" +
      "3YfRAoGAUxL/Eu5yvMK8SAt/dJK6FedngcM3JEFNplmtLYVLWhkIlNRGDwkg3I5K\n" +
      "y18Ae9n7dHVueyslrb6weq7dTkYDi3iOYRW8HRkIQh06wEdbxt0shTzAJvvCQfrB\n" +
      "jg/3747WSsf/zBTcHihTRBdAv6OmdhV4/dD5YBfLAkLrd+mX7iE=\n" +
      "-----END PRIVATE KEY-----"

  /**
   * header: {
   *   "alg": "RS256",
   *   "typ": "JWT"
   * },
   * payload: {
   *  "id": "86",
   *  "name": "Maxwell Smart",
   *  "email": "maxwell.smart@quintoandar.com.br",
   *  "role": "admin",
   *  "exp": 4102455600000
   * }
   *
   * (generated by https://jwt.io/)
   */
  @Shared
  def fakeJwt = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ODYsIm5hbWUiOiJNYXh3ZWxsIFNtYXJ0IiwiZW1haWwiOiJtYXh3ZWxsLnNtYXJ0QHF1aW50b2FuZGFyLmNvbS5iciIsInJvbGUiOiJhZG1pbiIsImV4cCI6NDEwMjQ1NTYwMDAwMH0.TMNdNzFKjrRqt72tdW5PMti1tee_13787UWkqP_sPsmWXkmtlChFgIzEKiWj0aR9NqcUrVWn0U4jGMpnD45BZ7k7CoRvROR06nrUkvJStptEU_H4dGbQId5oJcGzSz92sEJ7GtNmVfW2uiHK71ipY5jy7CosviHwDKAwEcMTJWJp58rbNBoO-esQb-CRztMvHZ5WSl0gxB6pXmglV95um6GAa_Qfve4lAEocTRci9WowHfVdhvPQDKsl7oMTod6Iz3OpPnPlPPH6XMAFs709juuHy3kCUxEv48rQVypUN-Cpn6a53wW1tq7RDJJnXv5bhvTm3421bMJV7kav7bdCmg"

  def setupSpec() {
    keycloakPublicKeyServiceMock.fetchKeycloakPublicKey() >> fakePublicKey2048bit
    keycloakSubject.quintoAndarKeycloakPublicKeyService = keycloakPublicKeyServiceMock
  }

  def "get payload from valid Keycloak jwt"() {
    when:
    def result = keycloakSubject.getPayload(fakeJwt)

    then:
    result.isPresent()

    and:
    def claims = result.get()
    claims.get("id") == 86
    claims.get("name") == "Maxwell Smart"
    claims.get("email") == "maxwell.smart@quintoandar.com.br"
    claims.get("role") == "admin"
    claims.get("exp") == 4102455600000
  }

  def "get payload from invalid Keycloak jwt throws exception"() {
    given:
    def jwtForOtherKeys = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywibmFtZSI6IkphbWVzIEJvbmQiLCJlbWFpbCI6Imphb" +
        "WVzLmJvbmRAcXVpbnRvYW5kYXIuY29tLmJyIiwicm9sZSI6ImFkbWluIn0.fwuOMtnmdKV7QeesDPWIsK-5Ipanv9PHPenzUWg5EOXG639z9" +
        "9EzEFn3Fcy-cBTqEPrzm1JorhfVvfABOEZaz7Kocv058lcUSnTQhVgAhu9GVo5CaQmPg6gDKBkndQ0n4wu-pW_c-q3AKr5auJW8gxs9AoJRH" +
        "1c5gQ-ablFJrOX4m2z17j81Aa-t8wM0jfbASJcu6omHaX5C4BLL7IzbYRUhE47lje3_D7SeXpciGPomI8Hl8hOo4dQpO8bZgO_uSTHDfTsoE" +
        "1ypOaXe8A5VVr1YDRpxlcBHvbxymCR0uJmeq2HCuAPyoN97KQHLrw5ehJ5TyLKTCDTm1aSjnl1O0g"

    when:
    def result = keycloakSubject.getPayload(jwtForOtherKeys)

    then:
    thrown(InvalidJwtException)
  }

}
